#- debug: var=ansible_facts
- include_vars: "../vars/default.yml"
- include_vars: "../vars/{{ ansible_os_family | lower }}.yml"
  ignore_errors: yes

- include: system.yml
  become: yes
 
# Create user library path
- name: Make R library user path
  shell: R -e 'dir.create(Sys.getenv()[["R_LIBS_USER"]], recursive = TRUE, showWarnings = FALSE)'
 
# Devtools
- name: Install CRAN devtools
  shell: R -e 'install.packages("devtools", dependencies = TRUE, repos = "https://cloud.r-project.org/")'
